/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculo;

import javax.swing.JOptionPane;

/**
 *
 * @author rftecnicos
 */
public class Monedas extends javax.swing.JFrame {

    /**
     * Creates new form Monedas
     */
    public Monedas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        numero = new javax.swing.JLabel();
        salir2 = new javax.swing.JButton();
        Dolares = new javax.swing.JRadioButton();
        Balboa = new javax.swing.JRadioButton();
        Euros = new javax.swing.JRadioButton();
        Cordoba = new javax.swing.JRadioButton();
        Quetzal = new javax.swing.JRadioButton();
        cantidad = new javax.swing.JTextField();
        resultado = new javax.swing.JLabel();
        respuesta = new javax.swing.JTextField();
        Calcular = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numero.setForeground(new java.awt.Color(255, 255, 255));
        numero.setText("Ingrese cantidad en lempiras:");
        getContentPane().add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        salir2.setBackground(new java.awt.Color(0, 0, 0));
        salir2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        salir2.setForeground(new java.awt.Color(255, 255, 255));
        salir2.setText("salir");
        salir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir2ActionPerformed(evt);
            }
        });
        getContentPane().add(salir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 80, -1));

        Dolares.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(Dolares);
        Dolares.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Dolares.setForeground(new java.awt.Color(255, 255, 255));
        Dolares.setText("Dolares");
        getContentPane().add(Dolares, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        Balboa.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(Balboa);
        Balboa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Balboa.setForeground(new java.awt.Color(255, 255, 255));
        Balboa.setText("Balboa");
        getContentPane().add(Balboa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        Euros.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(Euros);
        Euros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Euros.setForeground(new java.awt.Color(255, 255, 255));
        Euros.setText("Euros");
        getContentPane().add(Euros, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        Cordoba.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(Cordoba);
        Cordoba.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cordoba.setForeground(new java.awt.Color(255, 255, 255));
        Cordoba.setText("Cordoba");
        getContentPane().add(Cordoba, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        Quetzal.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(Quetzal);
        Quetzal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Quetzal.setForeground(new java.awt.Color(255, 255, 255));
        Quetzal.setText("Quetzal");
        getContentPane().add(Quetzal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));
        getContentPane().add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 140, -1));

        resultado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resultado.setForeground(new java.awt.Color(255, 255, 255));
        resultado.setText("Resultado:");
        getContentPane().add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));
        getContentPane().add(respuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 210, -1));

        Calcular.setBackground(new java.awt.Color(0, 0, 0));
        Calcular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Calcular.setForeground(new java.awt.Color(255, 255, 255));
        Calcular.setText("Calcular");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });
        getContentPane().add(Calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 80, -1));

        Titulo.setBackground(new java.awt.Color(0, 0, 0));
        Titulo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Convertidor de Moneda");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 190, 20));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione tipo de moneda: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo7.jpg"))); // NOI18N
        fondo2.setText("jLabel1");
        getContentPane().add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salir2ActionPerformed

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed

        double nu;
        double nu1 = 27.87;
        double nu2 = 24.55;
        double nu3 = 0.75;
        double nu4 = 3.19;
        double nu5 = 24.52;
        double resp = 0;

        nu = Double.parseDouble(cantidad.getText());

        if (Euros.isSelected()) {
            resp = nu / nu1;
        } else if (Dolares.isSelected()) {
            resp = nu / nu2;
        } else if (Cordoba.isSelected()) {
            resp = nu / nu3;
        } else if (Quetzal.isSelected()) {
            resp = nu / nu4;
        } else if (Balboa.isSelected()) {
            resp = nu / nu5;
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una de las opciones");
        }
        respuesta.setText("" + resp);


    }//GEN-LAST:event_CalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Monedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Monedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Monedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Monedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Monedas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Balboa;
    private javax.swing.JButton Calcular;
    private javax.swing.JRadioButton Cordoba;
    private javax.swing.JRadioButton Dolares;
    private javax.swing.JRadioButton Euros;
    private javax.swing.JRadioButton Quetzal;
    private javax.swing.JLabel Titulo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cantidad;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel numero;
    private javax.swing.JTextField respuesta;
    private javax.swing.JLabel resultado;
    private javax.swing.JButton salir2;
    // End of variables declaration//GEN-END:variables
}
